version: '3'
services:
  sh-database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - ./sh-database:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
volumes:
  sh-database: