version: '3.9'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      TYPEORM_HOST:
      TYPEORM_USERNAME: ''
      TYPEORM_PASSWORD: ''
      TYPEORM_DATABASE: ''
      TYPEORM_PORT: 3306
      TYPEORM_SYNCHRONIZE: 'true'
      TYPEORM_LOGGING: 'false'
      JWT_ACCESS_TOKEN: ''
