module.exports = {
  type: process.env.DB_TYPE,
  host: process.env.DB_HOST,
  port: process.env.DB_PORT,
  username: process.env.DB_USER,
  password: process.env.DB_PASS,
  database: process.env.DB_NAME,
  synchronize: process.env.SYNC,
  logging: true,
  entities: ['dist/entity/*.js', 'dist/entity/**/*.js'],
  migrations: ['dist/migration/**/*.js'],
  subscribers: ['dist/subscriber/**/*.js'],
  seeds: ['dist/entity/seeds/**/*{.ts,.js}'],
  factories: ['dist/entity/factories/**/*{.ts,.js}'],
  cli: {
    entitiesDir: 'dist/entity',
    migrationsDir: 'src/migration',
    subscribersDir: 'src/subscriber',
  },
};
