spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-sweet
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.flyway.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=

aws.accessKey=
aws.secretKey=
aws.cognito.userpool.id=
aws.cognito.app.clientid=