[tool.pytest.ini_options]
log_file = "./logs/api.log"
log_cli = "true"
log_cli_level = "CRITICAL"
log_cli_format = "%(message)s"
log_file_level = "DEBUG"
#log_file_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_file_format = "%(asctime)s %(levelname)-5s %(process)-5d %(filename)-20s %(message)s"
#log-format="%(asctime)s %(levelname)s %(message)s"
log_file_date_format = "%Y-%m-%d %H:%M:%S"

[pytest]
#env_override_existing_values = 1
env_files = ".env"
