@baseUrl = http://127.0.0.1
@basePort = 3000
@basePath = products

POST {{baseUrl}}:{{basePort}}/{{basePath}}/ HTTP/1.1
Content-Type: application/json

{
    "title": "Product 1",
    "description": "Description 1",
    "measurement": "G"
}

###

GET {{baseUrl}}:{{basePort}}/{{basePath}}/ HTTP/1.1
Content-Type: application/json

###

GET {{baseUrl}}:{{basePort}}/{{basePath}}/5 HTTP/1.1
Content-Type: application/json

###

PATCH {{baseUrl}}:{{basePort}}/{{basePath}}/1 HTTP/1.1
Content-Type: application/json

{
    "unique": true
}

###

DELETE {{baseUrl}}:{{basePort}}/{{basePath}}/5 HTTP/1.1
Content-Type: application/json

###

GET {{baseUrl}}:{{basePort}}/{{basePath}}/base HTTP/1.1
Content-Type: application/json