@baseUrl = http://127.0.0.1
@basePort = 3000
@basePath = appointments

POST {{baseUrl}}:{{basePort}}/{{basePath}}/ HTTP/1.1
Content-Type: application/json

{
    "name": "Test"
}

###

GET {{baseUrl}}:{{basePort}}/{{basePath}}/ HTTP/1.1
Content-Type: application/json

###

GET {{baseUrl}}:{{basePort}}/{{basePath}}/3 HTTP/1.1
Content-Type: application/json

###

PATCH {{baseUrl}}:{{basePort}}/{{basePath}}/3 HTTP/1.1
Content-Type: application/json

{
    "name": "Test Updated"
}

###

DELETE {{baseUrl}}:{{basePort}}/{{basePath}}/5 HTTP/1.1
Content-Type: application/json

###

GET {{baseUrl}}:{{basePort}}/{{basePath}}/5/transactions HTTP/1.1
Content-Type: application/json

###

GET {{baseUrl}}:{{basePort}}/{{basePath}}/5/customers HTTP/1.1
Content-Type: application/json

###

GET {{baseUrl}}:{{basePort}}/{{basePath}}/5/items HTTP/1.1
Content-Type: application/json