CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(255),
    password  VARCHAR(255),
    full_name VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

DROP TABLE "user" CASCADE;