# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  rest-testing:
    runs-on: ubuntu-latest
    needs: junit-testing
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ./.api_testing/requirements.txt ]; then pip install -r ./.api_testing/requirements.txt; fi
      - name: Make CERTS directory
        run: mkdir -p ./src/main/resources/certs
      - name: Generate RSA Private Key
        run: openssl genrsa -out ./src/main/resources/certs/keypair.pem 2048
      - name: Extract Public RSA Key
        run: openssl rsa -in ./src/main/resources/certs/keypair.pem -pubout -out ./src/main/resources/certs/public.pem
      - name: Format Private Key
        run: openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in ./src/main/resources/certs/keypair.pem -out ./src/main/resources/certs/private.pem
      - name: Run Application
        # Job hangs on this as the application launches and hold the console up
        run: docker compose -f docker-compose.test.yml up -d --build
      - name: Run API testing suite
        run: python ./.api_testing/main.py
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Make CERTS directory
      run: mkdir -p ./src/main/resources/certs
    - name: Generate RSA Private Key
      run: openssl genrsa -out ./src/main/resources/certs/keypair.pem 2048
    - name: Extract Public RSA Key
      run: openssl rsa -in ./src/main/resources/certs/keypair.pem -pubout -out ./src/main/resources/certs/public.pem
    - name: Format Private Key
      run: openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in ./src/main/resources/certs/keypair.pem -out ./src/main/resources/certs/private.pem
    - name: Test Application
      run: mvn test -Dspring.profiles.active=test
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
