name: Test and Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Make CERTS directory
        run: mkdir -p ./src/main/resources/certs
      - name: Generate RSA Private Key
        run: openssl genrsa -out ./src/main/resources/certs/keypair.pem 2048
      - name: Extract Public RSA Key
        run: openssl rsa -in ./src/main/resources/certs/keypair.pem -pubout -out ./src/main/resources/certs/public.pem
      - name: Format Private Key
        run: openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in ./src/main/resources/certs/keypair.pem -out ./src/main/resources/certs/private.pem
      - name: Test Application
        run: mvn test -Dspring.profiles.active=test
  build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true
    - name: Upload built JAR
      uses: actions/upload-artifact@v3
      with:
        name: sweet-hair-api
        path: target/sweethair-*.jar
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
