name: Test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Make CERTS directory
        run: mkdir -p ./src/main/resources/certs
      - name: Generate RSA Private Key
        run: openssl genrsa -out ./src/main/resources/certs/keypair.pem 2048
      - name: Extract Public RSA Key
        run: openssl rsa -in ./src/main/resources/certs/keypair.pem -pubout -out ./src/main/resources/certs/public.pem
      - name: Format Private Key
        run: openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in ./src/main/resources/certs/keypair.pem -out ./src/main/resources/certs/private.pem
      - name: Unit Test Application
        run: mvn test -Dspring.profiles.active=test
      - name: Build Application
        run: mvn clean package -Dapi_version=${{ github.job }}
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SOURCE: "target/*.jar"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"




  e2e-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r /api_testing/requirements.txt
      - name: Make CERTS directory
        run: mkdir -p ./src/main/resources/certs
      - name: Generate RSA Private Key
        run: openssl genrsa -out ./src/main/resources/certs/keypair.pem 2048
      - name: Extract Public RSA Key
        run: openssl rsa -in ./src/main/resources/certs/keypair.pem -pubout -out ./src/main/resources/certs/public.pem
      - name: Format Private Key
        run: openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in ./src/main/resources/certs/keypair.pem -out ./src/main/resources/certs/private.pem
      - name: Test Application
        run: mvn test -Dspring.profiles.active=test
      - name: Test E2E
        run: pytest ./api_testing